# Generated by Django 5.1.3 on 2026-07-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='default_max_recommendations',
            field=models.IntegerField(default=1),
        ),
    ]
