# Generated by Django 4.2.23 on 2025-06-28 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('max_recommendations', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filter_type', models.CharField(choices=[('issuer', 'Issuer'), ('reward_type', 'Reward Type'), ('annual_fee', 'Annual Fee'), ('signup_bonus', 'Signup Bonus')], max_length=20)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RoadmapCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_estimated_rewards', models.DecimalField(decimal_places=2, max_digits=12)),
                ('calculation_data', models.JSONField(default=dict)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('roadmap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculation', to='roadmaps.roadmap')),
            ],
        ),
        migrations.AddField(
            model_name='roadmap',
            name='filters',
            field=models.ManyToManyField(blank=True, to='roadmaps.roadmapfilter'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='cards.userspendingprofile'),
        ),
        migrations.CreateModel(
            name='RoadmapRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('apply', 'Apply for new card'), ('keep', 'Keep current card'), ('cancel', 'Cancel card'), ('upgrade', 'Upgrade card'), ('downgrade', 'Downgrade card')], max_length=20)),
                ('priority', models.IntegerField(default=1)),
                ('estimated_rewards', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reasoning', models.TextField()),
                ('recommended_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.creditcard')),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='roadmaps.roadmap')),
            ],
            options={
                'ordering': ['priority', 'estimated_rewards'],
                'unique_together': {('roadmap', 'card', 'action')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='roadmap',
            unique_together={('profile', 'name')},
        ),
    ]
