# Generated by Django 4.2.23 on 2025-07-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmapfilter',
            name='filter_type',
            field=models.CharField(choices=[('issuer', 'Issuer'), ('reward_type', 'Reward Type'), ('card_type', 'Card Type'), ('annual_fee', 'Annual Fee'), ('signup_bonus', 'Signup Bonus')], max_length=20),
        ),
    ]
