# Generated by Django 5.1.3 on 2026-07-11 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0002_alter_roadmap_max_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='privacy_setting',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='share_uuid',
            field=models.UUIDField(blank=True, default=None, help_text='Unique ID for sharing public roadmaps', null=True, unique=True),
        ),
    ]
