"""Add preferred issuer constraint to user profiles

Revision ID: 2956c67ee070
Revises: 9862f8ae3c83
Create Date: 2025-06-14 23:24:12.010149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2956c67ee070'
down_revision = '9862f8ae3c83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_issuer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'card_issuers', ['preferred_issuer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('preferred_issuer_id')

    # ### end Alembic commands ###
