"""Initial migration with recommendation_id

Revision ID: 9862f8ae3c83
Revises: 
Create Date: 2025-06-12 15:55:17.607038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9862f8ae3c83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommendation_id', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_recommendations_recommendation_id'), ['recommendation_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_recommendation_id'))
        batch_op.drop_column('recommendation_id')

    # ### end Alembic commands ###
