"""Update category system to be global admin-managed

Revision ID: 3f8886b4c63f
Revises: 9f3d5e7a2d4c
Create Date: 2025-06-05 22:54:35.839378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8886b4c63f'
down_revision = '9f3d5e7a2d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=100), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True, server_default='fas fa-tag'))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True, server_default='1'))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True, server_default='0'))
        batch_op.create_unique_constraint('uq_categories_name', ['name'])
        batch_op.drop_column('is_default')
        batch_op.drop_column('user_id')  # This will also drop the foreign key

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('is_default', sa.BOOLEAN(), nullable=True))
        batch_op.create_foreign_key('categories_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_constraint('uq_categories_name', type_='unique')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('is_active')
        batch_op.drop_column('icon')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
