"""Add aliases field to categories

Revision ID: 4aa696b42f06
Revises: 3f8886b4c63f
Create Date: 2025-06-09 22:49:35.235786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa696b42f06'
down_revision = '3f8886b4c63f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aliases', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('aliases')

    # ### end Alembic commands ###
