"""Initial migration

Revision ID: 6ba8de124c23
Revises: 
Create Date: 2025-04-19 13:03:34.918645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba8de124c23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('issuer', sa.String(length=50), nullable=False),
    sa.Column('annual_fee', sa.Float(), nullable=True),
    sa.Column('reward_categories', sa.Text(), nullable=True),
    sa.Column('offers', sa.Text(), nullable=True),
    sa.Column('signup_bonus_points', sa.Integer(), nullable=True),
    sa.Column('signup_bonus_value', sa.Float(), nullable=True),
    sa.Column('signup_bonus_spend_requirement', sa.Float(), nullable=True),
    sa.Column('signup_bonus_time_period', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_monthly_spend', sa.Float(), nullable=True),
    sa.Column('category_spending', sa.Text(), nullable=True),
    sa.Column('reward_preferences', sa.Text(), nullable=True),
    sa.Column('max_annual_fees', sa.Float(), nullable=True),
    sa.Column('max_cards', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_data', sa.Text(), nullable=False),
    sa.Column('total_estimated_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendations')
    op.drop_table('user_profiles')
    op.drop_table('credit_cards')
    # ### end Alembic commands ###
