# Generated by Django 5.1.3 on 2025-07-28 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('max_cards_per_period', models.IntegerField(default=5)),
                ('period_months', models.IntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RewardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('card_type', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='personal', max_length=20)),
                ('annual_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('signup_bonus_amount', models.IntegerField(blank=True, null=True)),
                ('signup_bonus_requirement', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.issuer')),
                ('primary_reward_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_reward_cards', to='cards.rewardtype')),
                ('signup_bonus_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signup_bonus_cards', to='cards.rewardtype')),
            ],
            options={
                'unique_together': {('name', 'issuer')},
            },
        ),
        migrations.CreateModel(
            name='SpendingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.IntegerField(default=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cards.spendingcategory')),
            ],
            options={
                'verbose_name_plural': 'Spending Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpendingCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.IntegerField(default=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_credits', to='cards.spendingcategory')),
            ],
            options={
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='CardCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('times_per_year', models.IntegerField(default=1)),
                ('weight', models.FloatField(default=1.0)),
                ('currency', models.CharField(blank=True, default='USD', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='cards.creditcard')),
                ('credit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_credits', to='cards.credittype')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.spendingcategory')),
                ('spending_credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_credits', to='cards.spendingcredit')),
            ],
        ),
        migrations.CreateModel(
            name='UserSpendingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('session_key',), ('user',)},
            },
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('opened_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.creditcard')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cards', to='cards.userspendingprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RewardCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_annual_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_categories', to='cards.creditcard')),
                ('reward_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.rewardtype')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.spendingcategory')),
            ],
            options={
                'unique_together': {('card', 'category', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='UserSpendingCreditPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values_credit', models.BooleanField(default=False)),
                ('spending_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.spendingcredit')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_credit_preferences', to='cards.userspendingprofile')),
            ],
            options={
                'unique_together': {('profile', 'spending_credit')},
            },
        ),
        migrations.CreateModel(
            name='UserCreditPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values_credit', models.BooleanField(default=False)),
                ('credit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.credittype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_preferences', to='cards.userspendingprofile')),
            ],
            options={
                'unique_together': {('profile', 'credit_type')},
            },
        ),
        migrations.CreateModel(
            name='SpendingAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.spendingcategory')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_amounts', to='cards.userspendingprofile')),
            ],
            options={
                'unique_together': {('profile', 'category')},
            },
        ),
    ]
