# Generated by Django 4.2.23 on 2025-06-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spendingcategory',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Spending Categories'},
        ),
        migrations.AddField(
            model_name='spendingcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spendingcategory',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='spendingcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='spendingcategory',
            name='sort_order',
            field=models.IntegerField(default=100),
        ),
    ]
