# Generated by Django 5.1.3 on 2025-08-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='url',
            field=models.URLField(blank=True, help_text='Primary card application URL', max_length=500),
        ),
    ]
