# Generated by Django 5.1.3 on 2025-07-19 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.FloatField(default=1.0)),
                ('currency', models.CharField(blank=True, default='USD', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='cards.creditcard')),
            ],
        ),
        migrations.DeleteModel(
            name='CardOffer',
        ),
    ]
