# Generated by Django 5.1.3 on 2025-07-28 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcredit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.spendingcategory'),
        ),
        migrations.AddField(
            model_name='cardcredit',
            name='times_per_year',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='SpendingCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.IntegerField(default=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_credits', to='cards.spendingcategory')),
            ],
            options={
                'ordering': ['sort_order', 'display_name'],
            },
        ),
        migrations.AddField(
            model_name='cardcredit',
            name='spending_credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_credits', to='cards.spendingcredit'),
        ),
        migrations.CreateModel(
            name='UserSpendingCreditPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values_credit', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_credit_preferences', to='cards.userspendingprofile')),
                ('spending_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.spendingcredit')),
            ],
            options={
                'unique_together': {('profile', 'spending_credit')},
            },
        ),
    ]
