# Generated by Django 5.1.3 on 2025-07-19 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_rename_cardoffer_to_cardcredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.IntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='cardcredit',
            name='credit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_credits', to='cards.credittype'),
        ),
        migrations.CreateModel(
            name='UserCreditPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values_credit', models.BooleanField(default=False)),
                ('credit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.credittype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_preferences', to='cards.userspendingprofile')),
            ],
            options={
                'unique_together': {('profile', 'credit_type')},
            },
        ),
    ]
