# Generated by Django 4.2.23 on 2025-07-01 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_spendingcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='personal', max_length=20),
        ),
    ]
