# Generated by Django 5.1.3 on 2025-08-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_add_referral_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspendingprofile',
            name='privacy_setting',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10),
        ),
        migrations.AddField(
            model_name='userspendingprofile',
            name='share_uuid',
            field=models.UUIDField(blank=True, default=None, help_text='Unique ID for sharing public profiles', null=True, unique=True),
        ),
    ]
