# Generated by Django 5.1.3 on 2026-07-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_merge_duplicate_travel_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='bonus_earned_date',
            field=models.DateField(blank=True, help_text='Date the signup bonus was earned (feeds issuer bonus-eligibility rules; approximated as opened_date + ~3 months when blank)', null=True),
        ),
    ]
