# Generated by Django 5.1.3 on 2026-07-04 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_usercard_bonus_earned_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercreditpreference',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cardcredit',
            name='credit_type',
        ),
        migrations.DeleteModel(
            name='UserCreditPreference',
        ),
        migrations.DeleteModel(
            name='CreditType',
        ),
    ]
