# Generated by Django 5.1.3 on 2025-07-19 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_add_credit_types_and_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendingcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='cards.spendingcategory'),
        ),
    ]
