# Generated by Django 5.1.3 on 2026-07-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_usercreditpreference_credit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendingcredit',
            name='stackable',
            field=models.BooleanField(default=True),
        ),
    ]
