# Generated by Django 5.1.3 on 2026-07-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_spendingcredit_stackable'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcredit',
            name='offer_type',
            field=models.CharField(blank=True, choices=[('statement_credit', 'Statement credit'), ('discount', 'Discount'), ('points_miles', 'Points / miles'), ('membership', 'Membership / subscription'), ('companion_pass', 'Companion pass'), ('other', 'Other')], help_text='How this credit pays out (display only, not read by the engine)', max_length=20),
        ),
        migrations.AddField(
            model_name='usercard',
            name='bonus_override',
            field=models.BooleanField(blank=True, help_text="Manual override of whether this card's signup bonus was earned: null=infer from issuer rules, True=earned it, False=did not (e.g. referred instead of applying, never activated)", null=True),
        ),
    ]
