# Generated by Django 5.1.3 on 2026-07-18 15:38
#
# Hand-ordered (see docs/PLAN_PHASE_K_HOUSEHOLDS.md, K1 #5): the new
# (user, card, owner) unique index must exist BEFORE the old unique_together
# is dropped, or MySQL raises error 1553 ("needed in a foreign key
# constraint") — the old index is what currently satisfies the FK index
# requirement on usercard.user_id.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_cardcredit_offer_type_usercard_bonus_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='personal', max_length=10)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='cards.userspendingprofile')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='profileentity',
            constraint=models.UniqueConstraint(fields=('profile', 'name'), name='uniq_entity_name_per_profile'),
        ),
        migrations.AddField(
            model_name='usercard',
            name='owner',
            field=models.ForeignKey(blank=True, help_text="NULL = the profile's primary entity (legacy rows / mocks). PROTECT so deleting an entity can't silently transplant its card history onto the primary and corrupt 5/24-style math.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.profileentity'),
        ),
        migrations.AddConstraint(
            model_name='usercard',
            constraint=models.UniqueConstraint(fields=('user', 'card', 'owner'), name='uniq_usercard_user_card_owner'),
        ),
        migrations.AlterUniqueTogether(
            name='usercard',
            unique_together=set(),
        ),
    ]
