# Generated by Django 5.1.3 on 2026-07-18 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_backfill_primary_entities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='owner',
            field=models.ForeignKey(blank=True, help_text="NULL = the profile's primary entity (legacy rows / mocks). RESTRICT (not PROTECT) so deleting an entity ON ITS OWN can't silently transplant its card history onto the primary and corrupt 5/24-style math, while still letting a whole User cascade-delete cleanly (PROTECT unconditionally blocks even when the referencing UserCard is being deleted in the same cascade; RESTRICT defers to that).", null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cards', to='cards.profileentity'),
        ),
    ]
