# Generated by Django 5.1.3 on 2026-07-18 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_usercard_owner_restrict'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('portal_url', models.URLField(blank=True, max_length=500, null=True)),
                ('transfer_partners', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='creditcard',
            name='reward_value_multiplier',
            field=models.DecimalField(decimal_places=4, default=0.01, max_digits=6),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='points_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='cards.pointsprogram'),
        ),
        migrations.CreateModel(
            name='PointsValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='cards.pointsprogram')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_valuations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('points_program', 'user')},
            },
        ),
    ]
