# Generated by Django 5.1.3 on 2026-07-18 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_pointsprogram_creditcard_reward_value_multiplier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreditUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_key', models.CharField(help_text='Derived from times_per_year: YYYY-MM, YYYY-QX, YYYY-HY, or YYYY', max_length=20)),
                ('used', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='cards.cardcredit')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_usages', to='cards.userspendingprofile')),
            ],
            options={
                'unique_together': {('profile', 'card_credit', 'period_key')},
            },
        ),
    ]
