# Generated by Django 5.1.3 on 2026-07-19 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_usercreditusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCardUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(help_text='e.g. chase.json', max_length=100)),
                ('external_card_id', models.CharField(help_text='andenacitelli cardId', max_length=100)),
                ('card_label', models.CharField(help_text="'{issuer} {name}' at proposal time", max_length=200)),
                ('section', models.CharField(help_text='e.g. annual_fee, signup_bonus, credits', max_length=50)),
                ('current_value', models.JSONField(help_text='The manually-curated value currently in the JSON')),
                ('proposed_value', models.JSONField(help_text="What andenacitelli's data suggests instead")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_updates', to='cards.creditcard')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('source_file', 'card_label', 'section'), name='uniq_open_pending_update')],
            },
        ),
    ]
