# Generated by Django 5.1.3 on 2026-07-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_pendingcardupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsprogram',
            name='currency_code',
            field=models.CharField(blank=True, default='', help_text="Matches CardCredit.currency (e.g. 'SOUTHWEST') so credits denominated in this program's points can be valued via PointsValuation.", max_length=20),
        ),
    ]
