# Generated by Django 5.1.3 on 2026-08-12 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_pointsprogram_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsprogram',
            name='redemption_methods',
            field=models.JSONField(blank=True, default=list, help_text='Ordered best to worst. Each entry: {method, cpp, verdict, note}, where verdict is one of best/good/poor/worst. Display-only curated content — cpp never feeds engine math (PointsValuation is the number the engine uses).'),
        ),
        migrations.AlterField(
            model_name='rewardcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_categories', to='cards.spendingcategory'),
        ),
    ]
