# Generated by Django 5.1.3 on 2026-08-12 02:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_pointsprogram_redemption_methods_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usercard',
            name='uniq_usercard_user_card_owner',
        ),
        migrations.AddConstraint(
            model_name='usercard',
            constraint=models.UniqueConstraint(condition=models.Q(('closed_date__isnull', True)), fields=('user', 'card', 'owner'), name='uniq_open_usercard_user_card_owner'),
        ),
    ]
